name: Build Artifacts
on:
  push:
    branches:
      - '**'

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: docker-integration-tests
            file: docker/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.dir }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ matrix.component.name }}
          provenance: false
